### ISSUE TITLE
Issue with Jest Test Cases

### ISSUE THREAD

**Issue by hammadgigalabs** [Donaldcwl/browser-image-compression#69]
Getting the following issue, when i run test cases

```
TypeError: Cannot read property 'drawImage' of null
    at drawImageInCanvas (/node_modules/browser-image-compression/dist/browser-image-compression.js:8:4058)
    at $Try_1_Post (/node_modules/browser-image-compression/dist/browser-image-compression.js:8:4203)
    at /node_modules/browser-image-compression/dist/browser-image-compression.js:8:4391
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Any ideas how to resolve this ?

**Comment by hustcc** [comment]
Because there is no browser env  in jest(jsdom), you can just try to use [jest-electrron](https://github.com/hustcc/jest-electron).
